# Generated by Django 5.0.3 on 2026-05-18 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_store_produ_categor_6683b7_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_weekly_top',
            field=models.BooleanField(default=False, help_text='Mark as Weekly Top Selling product'),
        ),
    ]
