# Generated by Django 5.0.3 on 2026-05-19 06:45
from django.db import migrations, models, connection


def create_offerbanner_if_not_exists(apps, schema_editor):
    if 'store_offerbanner' not in connection.introspection.table_names():
        schema_editor.create_model(apps.get_model('store', 'OfferBanner'))


def reverse_offerbanner(apps, schema_editor):
    if 'store_offerbanner' in connection.introspection.table_names():
        schema_editor.delete_model(apps.get_model('store', 'OfferBanner'))


class Migration(migrations.Migration):
    dependencies = [
        ('store', '0007_product_is_weekly_top'),
    ]
    operations = [
        migrations.CreateModel(
            name='OfferBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('tagline', models.CharField(blank=True, max_length=300)),
                ('max_discount', models.PositiveIntegerField(help_text='Max discount % to show e.g. 50')),
                ('theme', models.CharField(choices=[('eid_ul_fitr', 'Eid ul Fitr'), ('eid_ul_adha', 'Eid ul Adha'), ('winter', 'Winter Sale'), ('summer', 'Summer Sale'), ('monsoon', 'Monsoon Sale'), ('puja', 'Puja Season'), ('default', 'Default')], default='default', max_length=20)),
                ('show_from', models.DateTimeField(help_text='When to start showing this banner on site')),
                ('event_start', models.DateTimeField(help_text='Offer starts: countdown shows time left until this')),
                ('event_end', models.DateTimeField(help_text='Offer ends: countdown shows time left to end after start')),
                ('is_active', models.BooleanField(default=True, help_text='Master switch to enable/disable this banner')),
            ],
            options={
                'ordering': ['-show_from'],
            },
        ),
        migrations.RunPython(create_offerbanner_if_not_exists, reverse_offerbanner),
    ]