# Generated by Django 6.0.1 on 2026-07-09 11:40

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_product_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('button_text', models.CharField(default='Shop now', max_length=60)),
                ('is_active', models.BooleanField(default=True)),
                ('show_on_home', models.BooleanField(default=True, help_text='Only selected banners appear in the home slider.')),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['sort_order', 'name'], 'verbose_name_plural': 'categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='category',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Show this category on the home page.'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='store.category'),
        ),
        migrations.AddField(
            model_name='category',
            name='section',
            field=models.CharField(choices=[('clothing', 'Clothing'), ('electronics', 'Electronics'), ('toys', 'Toys'), ('garden', 'Garden'), ('home', 'Home & Living'), ('beauty', 'Beauty & Personal Care'), ('sports', 'Sports & Outdoors'), ('other', 'Other')], default='other', max_length=30),
        ),
        migrations.AddField(
            model_name='category',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Admin-selected product for category shelves'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_hot',
            field=models.BooleanField(default=False, help_text='Show as hot/most selling product on the home page'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent'], name='store_categ_parent__e56892_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['section'], name='store_categ_section_327f97_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_featured'], name='store_categ_is_feat_10990e_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_hot'], name='store_produ_is_hot_88e18e_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_featured'], name='store_produ_is_feat_a0ad0f_idx'),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Optional category to open when this banner is clicked.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hero_banners', to='store.category'),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Optional product to open when this banner is clicked.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hero_banners', to='store.product'),
        ),
        migrations.AddIndex(
            model_name='herobanner',
            index=models.Index(fields=['is_active', 'show_on_home'], name='store_herob_is_acti_d90d9b_idx'),
        ),
        migrations.AddIndex(
            model_name='herobanner',
            index=models.Index(fields=['sort_order'], name='store_herob_sort_or_14a9bb_idx'),
        ),
    ]
