# Generated by Django 6.0.1 on 2026-07-09 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_seed_marketplace_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='offer_banner',
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_percentage',
            field=models.PositiveSmallIntegerField(default=0, help_text='Discount % for this product (0 = no discount).'),
        ),
        migrations.DeleteModel(
            name='OfferBanner',
        ),
    ]
