# Generated by Django 5.1.7 on 2026-07-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_remove_product_offer_banner_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_active', 'parent'], name='store_categ_is_acti_6cbb7e_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_featured', 'is_active'], name='store_categ_is_feat_f5e5da_idx'),
        ),
        migrations.AddIndex(
            model_name='herobanner',
            index=models.Index(fields=['starts_at', 'ends_at'], name='store_herob_starts__aa9175_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_weekly_top'], name='store_produ_is_week_d6014a_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['discount_percentage'], name='store_produ_discoun_c58d7b_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_hot', 'is_weekly_top'], name='store_produ_is_hot_184c97_idx'),
        ),
    ]
