# Generated by Django 5.1.7 on 2026-07-12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_category_store_categ_is_acti_6cbb7e_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herobanner',
            name='product',
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='category',
            field=models.ForeignKey(help_text='Top-level category to open when this banner is clicked.', limit_choices_to={'is_active': True, 'parent__isnull': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hero_banners', to='store.category'),
        ),
    ]
